# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  http_method_override: false

  # Enables session with Redis support. Note that the session will ONLY be started if you read or write from it.
  session:
    enabled: true
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
    #save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    cookie_secure: auto
    cookie_samesite: lax

  #esi: true
  #fragments: true
  php_errors:
    log: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
