version: '3.6'
services:
  app:
    build: .docker/apachephp
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - .:/var/www
      - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
    user: "${VOLUME_USER_ID:-www-data}:www-data"
    links:
      - redis
    environment:
      APP_ENV: dev
      REDIS_URL: redis://cache
    networks:
      sfnetwork:
        aliases:
          - demo.local

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - sfnetwork

networks:
  sfnetwork:
    driver: bridge
